name: "Generate Typescript types and deploy them as npm package"
on:
  workflow_dispatch:
    inputs:
      release-flags:
        description: 'Release flags to passed to standard-version'
        default: ''
        type: string
        required: false
      dry-run:
        description: 'Do a dry-run (if selected would override release flags)'
        type: boolean
        default: false
        required: true
jobs:
  generate:
    name: "Generate Typescript types"
    runs-on: ubuntu-latest
    steps:
      - id: setup-dry-run-environment
        name: 'Setup dry-run environment'
        if: ${{ inputs.dry-run }}
        run: |
          echo "release-flags='-- --dry-run'" >> $GITHUB_ENV
      - id: setup-environment
        name: 'Setup environment'
        if: ${{ !inputs.dry-run }}
        run: |
          echo "release-flags=${{ inputs.release-flags }}" >> $GITHUB_ENV
      - id: setup-node
        name: 'Setup Node 18'
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - id: pull-latest-from-main
        name: 'Get latest code from main branch'
        uses: actions/checkout@v3
        with:
          ref: main
      - id: pull-latest-schema-files
        name: 'Get latest schema files'
        uses: actions/checkout@v3
        with:
          repository: 'cmxiv/google-workspace-addon-json-schema'
          ref: main
          path: schema
      - id: install-quicktype
        name: 'Install quicktype'
        run: |
          npm install -g quicktype
      - id: generate-types
        name: 'Generate types'
        run: |
          mkdir generated
          quicktype --just-types --lang typescript -s schema --src schema/Card.schema.json -o generated/Card.ts
          quicktype --just-types --lang typescript -s schema --src schema/CommonEvent.schema.json -o generated/Event.ts
          quicktype --just-types --lang typescript -s schema --src schema/Deployment.schema.json -o generated/Deployment.ts
          quicktype --just-types --lang typescript -s schema --src schema/RenderActionResponse.schema.json -o generated/RenderAction.ts
      - id: remove-schema-files
        name: 'Remove schema files'
        run: |
          rm -rf schema
      - id: create-release
        name: 'Create release'
        run: |
          npm install
          git config user.email "github-actions@example.com"
          git config user.name "GitHub Actions"
          npm run release ${{ env.release-flags }}
      - id: push-new-tag
        name: 'Push the new tag'
        if: ${{ inputs.do-release }}
        run: |
          git push --follow-tags origin main
          version=$(jq ".version" package.json --raw-output)
          echo "version=$version" >> $GITHUB_OUTPUT
      - id: upload-generated-types-as-artifacts
        name: 'Upload generated types as artifacts'
        if: ${{ inputs.do-release }}
        uses: actions/upload-artifact@v3
        with:
          name: google-workspace-addon-typescript-${{ steps.create-release.outputs.version }}
          path: generated