name: "Generate Typescript types and deploy them as npm package"
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  generate:
    name: "Generate Typescript types"
    runs-on: ubuntu-latest
    steps:
      - id: setup-node
        name: 'Setup Node 18'
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - id: pull-latest-from-main
        uses: actions/checkout@v3
        with:
          path: main
      - id: pull-latest-schema-files
        name: 'Get latest schema files'
        uses: actions/checkout@v3
        with:
          sparse-checkout: '*.schema.json'
          repository: 'cmxiv/google-workspace-addon-json-schema'
          ref: main
      - id: install-quicktype
        name: 'Install quicktype'
        run: |
          ls -lrta
          npm install -g quicktype
      - id: generate-types
        name: 'Generate types'
        run: |
          quicktype --just-types --lang typescript -s schema --src RenderActionResponse.schema.json -o RenderAction.ts
          quicktype --just-types --lang typescript -s schema --src Card.schema.json -o Card.ts
          quicktype --just-types --lang typescript -s schema --src CommonEvent.schema.json -o Event.ts
          quicktype --just-types --lang typescript -s schema --src Deployment.schema.json -o Deployment.ts
      - id: cleanup-schema-files
        name: 'Cleanup Schema files'
        run: |
          rm -rf *.schema.json
      - id: list-everything
        name: 'List everything'
        run: |
          ls -lrta
          git status