name: "Publish to npm"
on:
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - id: pull-latest-from-main
        name: 'Get latest code from main branch'
        uses: actions/checkout@v3
        with:
          ref: main
      - id: extract-tag-ref
        name: 'Extract tag from $GITHUB_REF'
        run: |
          npm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}
          npm config set //registry.npmjs.org/:username cmxiv
          npm config set //registry.npmjs.org/:email cmxiv914@gmail.com
          npm ci
          npm login --auth-type=legacy --registry=https://registry.npmjs.org
      - id: with-error
        name: 'with error'
        if: ${{ failure() }}
        run: |
          ls -lrta
          cp /home/runner/.npm/_logs/*.log .
          cat *.log