name: "Publish to npm"
on:
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - id: pull-latest-from-main
        name: 'Get latest code from main branch'
        uses: actions/checkout@v4
        with:
          ref: main
      - id: pull-latest-schema-files
        name: 'Get latest schema files'
        uses: actions/checkout@v4
        with:
          repository: 'cmxiv/google-workspace-addon-json-schema'
          ref: main
          path: schema
      - id: delete-schema-package-json-and-yarn-lock
        name: 'Delete schema package.json and yarn.lock'
        run: rm schema/package.json schema/yarn.lock
      - id: copy-remaining-schema-files
        name: 'Copy remaining schema files'
        run: cp -r schema/* .
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
      - id: generate-types
        name: 'Generate the typescript types'
        run: |
          npm i
          npm run build
      - id: publish
        name: 'Publish to NPM'
        run: npm publish --dry-run
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}